### ISSUE TITLE
Unexpected results

### ISSUE THREAD

**Issue by zichunxx** [ir-lab/irl_control#7]
Hi! Thanks for your generous sharing and work.

I am very interested in the admittance control implemented in `MuJoCo`. But when I try to run each of the examples, I find that the running result of each example deviates significantly from what is shown in `README`. 

Below are some of my runs:

* Insertion task

https://github.com/ir-lab/irl_control/assets/72594017/de5a4125-9f9b-4fb6-a2f4-18752e6aa960

* Force test

https://github.com/ir-lab/irl_control/assets/72594017/298b4c3e-001e-4b10-a5c4-19828e40a3a0

All the changes I made are as described [here](https://github.com/ir-lab/irl_control/issues/5#issuecomment-1872656826). 

Before I dive into this repo, I want to make sure what goes wrong regarding the above phenomenon.

Thanks in advance.

**Comment by mdrolet01** [comment]
Hello! I apologize for the late reply. Last time I ran these examples, I didn't experience this behavior, but I have since moved on to the official mujoco API (so I am no longer using mujoco-py). If you are still interested, you may find this version of irl_control easier to use/install:
https://github.com/ir-lab/bimanual-imitation
There is an example of a four peg insertion task, which you can use as inspiration for other tasks.

**Comment by zichunxx** [comment]
Thanks for your reply @mdrolet01! 

Congratulations on the acceptance of your paper, which will inspire me a lot.

BTW, I found the paper link on your project website does not link to the original paper.

**Comment by mdrolet01** [comment]
@zichunxx no problem- and thanks, wishing you the best of luck!
I've updated the website with the link to the paper :)
